name: API reference refresh

## Action that will be executed manually
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dokka:
    name: Generate API documentation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up JDK
        uses: actions/setup-java@v3.5.0
        with:
          java-version: '11'
          distribution: 'zulu'
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Update Username from Secrets
        env:
          MOCK_USERNAME: ${{ secrets.TELNYX_SIP_USER }}
        run: echo MOCK_USERNAME="$MOCK_USERNAME" > ./local.properties

      - name: Add new line
        run: echo -e "\n" >> ./local.properties

      - name: Update Password from Secrets
        env:
          MOCK_PASSWORD: ${{ secrets.TELNYX_SIP_PASSWORD }}
        run: echo MOCK_PASSWORD="$MOCK_PASSWORD" >> ./local.properties

      - name: Clean
        run: ./gradlew clean

      - name: Read local.properties
        id: properties
        uses: juliangruber/read-file-action@v1
        with:
          path: ./local.properties
      - name: Echo local.properties
        run: echo "${{ steps.package.outputs.content }}"

      - name: Generate documentation with Dokka
        run: ./gradlew dokkaHtml

      - name: Setup Git user (GitHub Actions bot)
        run: |
          git config user.name TelnyxIntegrations
          git config user.email integrations@telnyx.com

      - name: Configure git push.autoSetupRemote
        run: |
          git config push.autoSetupRemote true

      - name: Create new branch name for docs
        run: |
          BRANCH_NAME="update/docs-$(date +'%Y%m%d%H%M%S')"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request using GitHub Actions bot
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            docs/
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: TelnyxIntegrations <integrations@telnyx.com>
          base: main
          branch: ${{ env.branch_name }}
          delete-branch: true
          title: '[docs] Update generated HTML documentation'
          commit-message: "docs: Generated full documentation"
          body: "This PR updates the full documentation generated by dokkaHtml."
          labels: "documentation, auto-generated"
          draft: false